#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
DATABASE_URL = data.get("DATABASE_URL", "${DATABASE_URL}") 
MODE = data.get("MODE", "worker") 
WORKER_GROUP = data.get("WORKER_GROUP", "native") 
NUM_WORKERS = data.get("NUM_WORKERS", "8") 
SLEEP_QUEUE = data.get("SLEEP_QUEUE", "200") 
 
windmill_worker_native = { 
 "DATABASE_URL" : DATABASE_URL ,
 "MODE" : MODE ,
 "WORKER_GROUP" : WORKER_GROUP ,
 "NUM_WORKERS" : NUM_WORKERS ,
 "SLEEP_QUEUE" : SLEEP_QUEUE ,
} 
agent.write_envfile("windmill_worker_native.env", windmill_worker_native) 
