#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()
POSTGRES_PASSWORD = generate_random_password(16)
POSTGRES_DB = data.get("POSTGRES_DB", "windmill")
DATABASE_URL = (
    f"postgres://postgres:{POSTGRES_PASSWORD}@db-app/{POSTGRES_DB}?sslmode=disable"
)
db = {
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB,
    "DATABASE_URL": DATABASE_URL,
}
agent.write_envfile("db.env", db)
