#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e -o pipefail

mkdir -vp restore

# Create restore script
cat - >restore/monica_restore.sh <<'EOS'
# Read dump file from standard input:
pg_restore --no-owner --no-privileges -U postgres -d db
ec=$?
docker_temp_server_stop
exit $ec
EOS

# Run the restore container
podman run \
	--rm \
	--interactive \
	--network=none \
	--volume=./restore:/docker-entrypoint-initdb.d/:Z \
	--volume=postgres-data:/var/lib/postgresql/data:Z \
	--replace --name=restore_db \
	--env-file db.env \
	"${POSTGRES_IMAGE}" <db.pg_dump

# Clean up
rm -rfv restore/ db.pg_dump
